all:	
	make -C v400
	make -C v407	
	make -C v500
	make -C v504
	make -C v601
	make -C v606
	make -C v702
	make -C v703
	make -C v704
	make -C vUS1
	make -C vUS2
	make -C vUS3

clean:
	make -C v400 clean
	make -C v407 clean
	make -C v500 clean
	make -C v504 clean
	make -C v601 clean
	make -C v606 clean
	make -C v702 clean
	make -C v703 clean
	make -C v704 clean
	make -C vUS1 clean
	make -C vUS2 clean
	make -C vUS3 clean

.PHONY: all clean
